return {
  -- add gruvbox
  { "ellisonleao/gruvbox.nvim" },
  {
    "loctvl842/monokai-pro.nvim",
    lazy = false,
    config = function()
      require("gruvbox").setup({
        terminal_colors = true, -- add neovim terminal colors
        undercurl = true,
        underline = true,
        bold = true,
        italic = {
          strings = true,
          emphasis = true,
          comments = true,
          operators = false,
          folds = true,
        },
        strikethrough = true,
        invert_selection = false,
        invert_signs = false,
        invert_tabline = false,
        inverse = true, -- invert background for search, diffs, statuslines and errors
        contrast = "", -- can be "hard", "soft" or empty string
        palette_overrides = {
          dark0_hard = "#1d2021",
          dark0 = "#282828",
          dark0_soft = "#32302f",
          dark1 = "#3c3836",
          dark2 = "#504945",
          dark3 = "#665c54",
          dark4 = "#7c6f64",
          light0_hard = "#f9f5d7",
          light0 = "#fbf1c7",
          light0_soft = "#f2e5bc",
          light1 = "#ebdbb2",
          light2 = "#d5c4a1",
          light3 = "#bdae93",
          light4 = "#a89984",
          bright_red = "#fb4934",
          -- bright_green = "#b8bb26",
          bright_green = "#8ec07c",
          bright_yellow = "#fabd2f",
          bright_blue = "#83a598",
          bright_purple = "#d3869b",
          bright_aqua = "#8ec07c",
          bright_orange = "#fe8019",
          neutral_red = "#cc241d",
          -- neutral_green = "#98971a",
          neutral_green = "#8ec07c",
          neutral_yellow = "#d79921",
          neutral_blue = "#458588",
          -- neutral_purple = "#b16286",
          neutral_purple = "#8ec07c",
          neutral_aqua = "#689d6a",
          neutral_orange = "#d65d0e",
          faded_red = "#9d0006",
          faded_green = "#79740e",
          faded_yellow = "#b57614",
          faded_blue = "#076678",
          faded_purple = "#8f3f71",
          faded_aqua = "#427b58",
          faded_orange = "#af3a03",
          dark_red_hard = "#792329",
          dark_red = "#722529",
          dark_red_soft = "#7b2c2f",
          light_red_hard = "#fc9690",
          light_red = "#fc9487",
          light_red_soft = "#f78b7f",
          dark_green_hard = "#5a633a",
          dark_green = "#62693e",
          dark_green_soft = "#686d43",
          light_green_hard = "#d3d6a5",
          light_green = "#d5d39b",
          light_green_soft = "#cecb94",
          dark_aqua_hard = "#3e4934",
          dark_aqua = "#49503b",
          dark_aqua_soft = "#525742",
          light_aqua_hard = "#e6e9c1",
          light_aqua = "#e8e5b5",
          light_aqua_soft = "#e1dbac",
          gray = "#928374",
        },
        overrides = {},
        dim_inactive = false,
        transparent_mode = false,
      })
    end,
  },
  {
    "uloco/bluloco.nvim",
    lazy = false,
    dependencies = { "rktjmp/lush.nvim" },
    -- config = function()
    --   -- your optional config goes here, see below.
    -- end,
  },
  --   {
  --     local dark = {
  --   -- syntax
  --   bg                    = hsl("#282C34"),
  --   bgFloat               = isTransparentFloatWindow and "NONE" or hsl("#21242D"),
  --   fg                    = hsl("#ABB2BF"),
  --   cursor                = hsl("#FFCC00"),
  --   keyword               = hsl("#10B1FE"),
  --   comment               = hsl("#636D83"),
  --   punctuation           = hsl("#7A82DA"),
  --   method                = hsl("#3FC56B"),
  --   type                  = hsl("#FF6480"),
  --   string                = hsl("#F9C859"),
  --   number                = hsl("#FF78F8"),
  --   constant              = hsl("#9F7EFE"),
  --   tag                   = hsl("#3691FF"),
  --   attribute             = hsl("#FF936A"),
  --   property              = hsl("#CE9887"),
  --   parameter             = hsl("#8bcdef"),
  --   label                 = hsl("#50acae"),
  --   module                = hsl("#FF839B"),
  --   primary               = hsl("#3691ff"),
  --   selection             = hsl("#274670"),
  --   search                = hsl("#1A7247"),
  --   diffAdd               = hsl("#105B3D"),
  --   diffChange            = hsl("#10415B"),
  --   diffDelete            = hsl("#522E34"),
  --   added                 = hsl("#177F55"),
  --   changed               = hsl("#1B6E9B"),
  --   deleted               = hsl("#A14D5B"),
  --   diffText              = hsl("#10415B").lighten(12),
  --   error                 = hsl("#ff2e3f"),
  --   errorBG               = hsl("#FDCFD1"),
  --   warning               = hsl("#da7a43"),
  --   warningBG             = hsl("#F2DBCF"),
  --   info                  = hsl("#3691ff"),
  --   infoBG                = hsl("#D4E3FA"),
  --   hint                  = hsl("#7982DA"),
  --   mergeCurrent          = hsl("#4B3D3F"),
  --   mergeCurrentLabel     = hsl("#604B47"),
  --   mergeIncoming         = hsl("#2F476B"),
  --   mergeIncomingLabel    = hsl("#305C95"),
  --   copilot               = hsl('#95A922'),
  --   terminalBlack         = hsl("#42444d"),
  --   terminalRed           = hsl("#fc2e51"),
  --   terminalGreen         = hsl("#25a45c"),
  --   terminalYellow        = hsl("#ff9369"),
  --   terminalBlue          = hsl("#3375fe"),
  --   terminalMagenta       = hsl("#9f7efe"),
  --   terminalCyan          = hsl("#4483aa"),
  --   terminalWhite         = hsl("#cdd3e0"),
  --   terminalBrightBlack   = hsl("#8f9aae"),
  --   terminalBrightRed     = hsl("#ff637f"),
  --   terminalBrightGreen   = hsl("#3fc56a"),
  --   terminalBrightYellow  = hsl("#f9c858"),
  --   terminalBrightBlue    = hsl("#10b0fe"),
  --   terminalBrightMagenta = hsl("#ff78f8"),
  --   terminalBrightCyan    = hsl("#5fb9bc"),
  --   terminalBrightWhite   = hsl("#ffffff"),
  --   rainbowRed            = hsl("#FF6666"),
  --   rainbowYellow         = hsl("#f4ff78"),
  --   rainbowBlue           = hsl("#44A5FF"),
  --   rainbowOrange         = hsl("#ffa023"),
  --   rainbowGreen          = hsl("#92f535"),
  --   rainbowViolet         = hsl("#ff78ff"),
  --   rainbowCyan           = hsl("#28e4eb"),
  --   rainbowIndigo         = hsl("#9F7EFE"),
  -- }
  --
  {
    "shatur/neovim-ayu",
    lazy = false,
    config = function()
      require("ayu").setup({
        overrides = {
          Statement = { fg = "#10b0fe" },
          Type = { fg = "#ff6d7e" },
          -- String = { fg = "#3fc56a" },
          -- String = { fg = "#a9dc76" },
          Constant = { fg = "#ff78ff" },
          LineNr = { fg = "#274670" },
          -- DiagnosticError = { bg = "#0B0E14" },
        },
      })
    end,
  },
  { "rebelot/kanagawa.nvim" },
  { "sainnhe/edge", lazy = false },
  -- Configure LazyVim to load gruvbox
  {
    "LazyVim/LazyVim",
    opts = {
      -- colorscheme = "monokai-pro-octagon",
      -- colorscheme = "bluloco",
      -- colorscheme = "gruvbox",
      -- colorscheme = "tokyonight-night",
      colorscheme = "ayu-mirage",
      -- colorscheme = "kanagawa",
      -- colorscheme = "edge",
    },
  },

  -- change trouble config
}
