set -g @plugin 'tmux-plugins/tmp'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'catppuccin/tmux#v2.1.2'
set -ogq u/catppuccin_window_test "#W"
set -ogq u/catppuccin_window_current_test "#W"
set -g default-terminal "tmux-256color"
set -g mouse on

run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux
run ~/.config/tmux/plugins/tmux-plugins/tmux-cpu/cpu.tmux
