set -g @plugin 'tmux-plugins/tmp'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'catppuccin/tmux#v2.1.2'
set -ogq u/catppuccin_window_test "#W"
set -ogq u/catppuccin_window_current_test "#W"

set -g @catppuccin_flavor "mocha"
set -g @catppuccin_status_background "none"
set -g @catppuccin_window_status_style "none"
set -g @catppuccin_pane_status_enabled "off"
set -g @catppuccin_pane_border_status "off"

# Configure Tmux
set -g status-position bottom
# set -g status-style "bg=#{@thm_bg}"
# set -g status-justify "absolute-centre"

set -g default-terminal "tmux-256color"
set -g mouse on

set -g base-index 1 
set -g pane-base-index 1
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux
run ~/.config/tmux/plugins/tmux-plugins/tmux-cpu/cpu.tmux


bind-key -r f run-shell "tmux neww ~/sessionizer.sh"
